title: Unofficial danbooru API | whdzera
username: whdzera
email: whdzera@gmail.com
baseurl: "/unofficial-danbooru-api"
url: "" 
twitter_username: whdzera
github_username:  rokhimin/unofficial-danbooru-api
donate_username: whdzera